services:
  db:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}_db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - ./db:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: ${PROJECT_NAME}_wp
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${WP_PORT}:80"
      - "5050:5050" 
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost:${WP_PORT}');
        define('WP_SITEURL', 'http://localhost:${WP_PORT}');
    volumes:
      - wp_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content:delegated
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}_pma
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

volumes:
  wp_data:
